### ISSUE TITLE
Packaging: place staslib in arch-independent path

### ISSUE THREAD

**Issue by tbzatek** [linux-nvme/nvme-stas#102]
https://github.com/linux-nvme/nvme-stas/blob/3b8e8d948c935fb7d2aeb5d48d83924a0e284649/staslib/meson.build#L31-L35

One more issue found during packaging - as this is a _pure_ Python project with no architecture-specific code, we aim for a single package for all architectures (i.e. _noarch_ in rpm world). However, the meson project places `staslib` in architecture-specific directory (e.g. `/usr/lib64`) and also ignores any supplied `libdir` meson argument.

Setting `pure: true` in the code snippet above seems to do the trick, although I'm not sure what else would it break.

Also, per https://mesonbuild.com/Python-3-module.html the `python3` meson module is deprecated.

**Comment by martin-belanger** [comment]
Thanks for pointing this out. I will try with "pure: true" to make sure it doesn't break anything.

**Comment by martin-belanger** [comment]
@tbzatek - I tried the change on Ubuntu, Fedora, and SLES. On Ubuntu it makes no difference, but on Fedora/SLES it moves the packages from `/usr/lib64/` to `/usr/lib/`. Everything still works normally, so I should be able to go ahead with the change.

I noticed that the same change will be needed for libnvme as well.

This change will need to be released with a different version number, probably v1.0.1.

**Comment by tbzatek** [comment]
> I noticed that the same change will be needed for libnvme as well.

It's a different scenario - `libnvme` is architecture-dependent, while `nvme-stas` is pure Python code and any arch-dependent code lies in one layer below. I suppose the meson module might have some detection logic though.

**Comment by martin-belanger** [comment]
> It's a different scenario - `libnvme` is architecture-dependent, while `nvme-stas` is pure Python code and any arch-dependent code lies in one layer below. I suppose the meson module might have some detection logic though.

Ok got it. Because the libnvme Python bindings are SWIG-generated C++ code, they are in fact architecture-dependent. Makes sense.

**Comment by martin-belanger** [comment]
> Also, per https://mesonbuild.com/Python-3-module.html the `python3` meson module is deprecated.

BTW, I am not using the deprecated Python module. `python3` is just the name of a variable, which is defined in the top-level `meson.build` as follows:
```
python3 = import('python').find_installation('python3')
```

**Comment by martin-belanger** [comment]
Issue resolved by this pull request: https://github.com/linux-nvme/nvme-stas/pull/104

Once all the tests have completed, I will release v1.0.1.

**Comment by martin-belanger** [comment]
@tbzatek - v1.0.1 has been released
