### ISSUE TITLE
Add tag for packaging

### ISSUE THREAD

**Issue by igaw** [linux-nvme/nvme-stas#2]
Would it possible to add an initial tag, e.g. v1.0 or v1.0-rc0? It would make the packaging simpler.

**Comment by martin-belanger** [comment]
Yes. Will do.

**Comment by martin-belanger** [comment]
Issue resolved by this: https://github.com/linux-nvme/nvme-stas/releases/tag/v1.0-rc0

**Comment by igaw** [comment]
Thanks!
