### ISSUE TITLE
Udev test issues with esoteric network interfaces

### ISSUE THREAD

**Issue by ogayot** [linux-nvme/nvme-stas#407]
Hello,

(as discussed in https://github.com/linux-nvme/nvme-stas/pull/406, I'm filing another issue for the sake of completeness)

In Ubuntu, we have an openstack infrastructure that we can use for testing things in VMs (this is different from the infrastructure where autopkgtests run). When running the test-suite in a VM deployed by this openstack, there are multiple udev test-cases failing:

* Test Case 1
* Test Case 8
* Test Case 11
* Test Case 12
* Legacy Test Case D6
* Legacy Test Case F6

What is particular in these machines is the presence of a VXLAN network interface having a link-local IPv6 set (it is also a member of a bridge but I don't think this is relevant). I am not exactly sure what this type of interface does but I managed to reproduce the failure after running the following steps:

```bash
ip link add type vxlan id 1234 dstport 0
ip link set vxlan0 up 
```
I also reproduced the failures with `dummy` interfaces but I'm not sure if that's a real use-case.

```bash
ip link add type dummy
ip link set dummy0 up
```

```python
======================================================================
FAIL: test__cid_matches_tid (__main__.Test.test__cid_matches_tid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test-udev.py", line 520, in test__cid_matches_tid
    self.assertEqual(
AssertionError: True != False : Test Case 1 failed

----------------------------------------------------------------------
Ran 6 tests in 0.025s

FAILED (failures=1)
```

Thanks,
Olivier

**Comment by martin-belanger** [comment]
Fixed by https://github.com/linux-nvme/nvme-stas/pull/409

**Comment by ogayot** [comment]
Excellent, thanks for the quick fix!
